version: "2"
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - 5432
  web:
    build: .
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --reload'
    ports:
      - "8099:8000"
    volumes:
      - .:/opt/webapp
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=default
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:alpine
  worker:
    build: .
    command: celery worker --app=worker.app --loglevel=info --logfile=../logs/celery.log
    volumes:
      - .:/opt/webapp
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: 'no'
    depends_on:
      - web
      - redis
  dashboard:
    build: .
    command: celery -A worker.app flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=myemail@gmail.com
    ports:
      - '5050:80'
    depends_on:
      - postgres